# Generated by Django 6.1.1 on 2026-09-25 19:58

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_location_geometry_source_location_lat_location_lon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="dirty_fields",
            field=events.models.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("source_url", "source_url"),
                        ("source_license", "source_license"),
                        ("name", "name"),
                        ("description", "description"),
                        ("formatted_description", "formatted_description"),
                        ("url", "url"),
                        ("start_date", "start_date"),
                        ("start_time", "start_time"),
                        ("end_date", "end_date"),
                        ("end_time", "end_time"),
                        ("location", "location"),
                        ("performer", "performer"),
                        ("mode", "mode"),
                        ("organizer", "organizer"),
                        ("visible", "visible"),
                    ],
                    max_length=63,
                ),
                blank=True,
                default=list,
            ),
        ),
    ]
