version: 2

updates:
  # frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "component/frontend"
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  # github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  # backend
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "component/backend"
    groups:
      backend-dependencies:
        patterns:
          - "*"

  # docker compose / container images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "component/docker"
    groups:
      docker-dependencies:
        patterns:
          - "*"
