FROM python:3.14 AS django

COPY --from=ghcr.io/astral-sh/uv:0.12.19 /uv /uvx /bin/

WORKDIR /app

ENV PYTHONFAULTHANDLER=1 PYTHONUNBUFFERED=1 \
  UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy UV_NO_CACHE=1 UV_PYTHON_DOWNLOADS=0 \
  UV_PROJECT_ENVIRONMENT=/opt/venv PATH="/opt/venv/bin:$PATH"

COPY pyproject.toml uv.lock ./

RUN uv sync --locked --no-dev

COPY mj mj
COPY events events
COPY scraping scraping
COPY templates templates
COPY manage.py ./

RUN useradd -u 5000 app && chown app:app /app
USER app:app

CMD ["gunicorn", "--bind", ":8000", "--no-control-socket", "-k", "uvicorn_worker.UvicornWorker", "mj.asgi:application"]

# static files
FROM django AS staticfiles-prep

COPY .env.example .env

RUN python manage.py collectstatic --no-input

# precompress with gzip
RUN find /app/static \
  -type f -regextype posix-extended \
  -size +512c \
  -iregex '.*\.(css|csv|html?|js|svg|txt|xml|json|webmanifest|ttf)' \
  -exec gzip -9 -k '{}' \;

FROM docker.io/nginxinc/nginx-unprivileged:1.23 AS staticfiles

COPY --chown=101 deployment/api-static.nginx.conf /etc/nginx/conf.d/default.conf

COPY --chown=101 --from=staticfiles-prep /app/static /www/static

# Repeat django stage to make it the final one
FROM django
